In [1]:
import numpy as np

### Q1

In [40]:
matrix = np.identity(3, dtype=float)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Q2

In [41]:
array = np.random.rand(10)

print(array)

[0.69703814 0.41834459 0.52438177 0.93388426 0.95763445 0.25255486
 0.19076544 0.05345448 0.63137126 0.3805625 ]


### Q3

In [42]:
random_array = np.random.randint(0, 100, (3, 4))

print(random_array)

[[98 48 51 75]
 [19 55  1 45]
 [64 25 30 29]]


### Q4

In [43]:
def my_custom_function(x):
  """
  A custom function that calculates the square of the input value.
  """
  return x**2


custom_array = np.fromfunction(my_custom_function, (5,))

print(custom_array)

[ 0.  1.  4.  9. 16.]


### Q5

In [44]:
one_d_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

two_d_array = one_d_array.reshape(3, 3)

print(two_d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Q6

In [45]:
ones_array = np.ones((3, 3), dtype= int)
print(ones_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### Q7

In [46]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

common_elements = np.intersect1d(a, b)
print(common_elements)

[2 4]


### Q8

In [47]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


### Q9

In [48]:
a = np.arange(15)

print(a[:6])

[0 1 2 3 4 5]


### 10

In [49]:

array = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])


cleaned_array = np.nan_to_num(array)

print(cleaned_array)

[1. 2. 3. 0. 5. 6. 7. 0.]


### Q11

In [50]:
one_d_array = np.arange(1, 21)

# Create a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20
two_d_array = np.arange(1, 21).reshape(4, 5)

print("1D array:", one_d_array)
print("2D array:", two_d_array)

1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2D array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### Q12

In [51]:
arr = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8]],
               [[9, 10, 11, 12],
                [13, 14, 15, 16]]])


shape = arr.shape
print("Shape:", shape)  # Output: (2, 3, 4)


size = arr.size
print("Size:", size)  # Output: 24


ndim = arr.ndim
print("Number of dimensions:", ndim)  # Output: 3


dtype = arr.dtype
print("Data type:", dtype)  # Output: int32 (or your default integer type)


arr = arr.astype(np.float64)

dtype = arr.dtype
print("New data type:", dtype)  

Shape: (2, 2, 4)
Size: 16
Number of dimensions: 3
Data type: int32
New data type: float64


### Q13

In [52]:
one_d_array = np.arange(12)

two_d_array = one_d_array.reshape(3, 4)

flattened_array = two_d_array.ravel()

if np.array_equal(one_d_array, flattened_array):
  print("The flattened array matches the original.")
else:
  print("The flattened array does not match the original.")

The flattened array matches the original.


### Q14

In [53]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition
addition = a + b
print("Addition:", addition)  

# Element-wise subtraction
subtraction = a - b
print("Subtraction:", subtraction)  

# Element-wise multiplication
multiplication = a * b
print("Multiplication:", multiplication)  

# Element-wise division
division = a / b
print("Division:", division) 

# Division by zero:
c = np.array([0, 1, 2])
division_with_zero = a / c
print("Division with zero:", division_with_zero) 

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Division with zero: [inf 2.  1.5]


C:\Users\sahil\AppData\Local\Temp\ipykernel_6372\1041951278.py:22: RuntimeWarning: divide by zero encountered in divide
  division_with_zero = a / c


When dividing by zero, NumPy produces a RuntimeWarning and sets the result to inf (infinity)

### Q15

In [54]:
array_2d = np.array([[1],
                     [2],
                     [3]])


array_1d = np.array([4, 5, 6])

# Perform element-wise addition using broadcasting
result = array_2d + array_1d

print(result)
### each element of the 1D array is added to the corresponding element in each row of the 2D array.

[[5 6 7]
 [6 7 8]
 [7 8 9]]


### Q16

In [5]:
random_array = np.random.randint(0, 11, (4, 5))


mask = random_array > 5

# Replace elements greater than 5 with the value 5
random_array[mask] = 5

print(random_array)

[[1 5 5 5 5]
 [5 5 5 3 0]
 [5 1 1 0 5]
 [0 5 5 4 5]]


### Q17

In [8]:
random_array = np.random.randint(0, 10, (4, 4))

# Extract the entire second row
second_row = random_array[1, :]

# Extract the last column
last_column = random_array[:, -1]

# Extract the subarray consisting of the first two rows and first two columns
subarray = random_array[:2, :2]

print("Random array:")
print(random_array)

print("\nSecond row:")
print(second_row)

print("\nLast column:")
print(last_column)

print("\nSubarray:")
print(subarray)

Random array:
[[7 6 7 8]
 [4 4 9 9]
 [8 4 6 6]
 [3 1 9 6]]

Second row:
[4 4 9 9]

Last column:
[8 9 6 6]

Subarray:
[[7 6]
 [4 4]]


### Q18

EDA: Analyzing Sales Data
Analyze sales data to identify trends and patterns.

AI: Image Processing
Perform image filtering (e.g., blurring) using NumPy.

ML: Feature Engineering
Create new features from existing data for a machine learning model.

DL: Neural Network Implementation
Implement a simple neural network for classification.               

### Q19

### Q20

In [9]:
one_d_array = np.arange(27)

## Reshape the 1D array into a 3x3x3 3D array
three_d_array = one_d_array.reshape(3, 3, 3)

## Flatten the 3D array back into 1D array
flattened_array = three_d_array.flatten()

## Compare the flattened array with the original
if np.array_equal(one_d_array, flattened_array):
    print("The flattened array matches the original.")
else:
    print("The flattened array does not match the original.")

The flattened array matches the original.
