In [2]:
import numpy as np

## Q21

In [4]:
import timeit
matrix_size = 1000

# Create random matrices
matrix_a = np.random.rand(matrix_size, matrix_size)
matrix_b = np.random.rand(matrix_size, matrix_size)

# Measure time for np.dot()
time_dot = timeit.timeit(lambda: np.dot(matrix_a, matrix_b), number=100)

# Measure time for @
time_at = timeit.timeit(lambda: matrix_a @ matrix_b, number=100)

# Print results
print("Time taken for np.dot():", time_dot)
print("Time taken for @:", time_at)

# Verify results
result_dot = np.dot(matrix_a, matrix_b)
result_at = matrix_a @ matrix_b

if np.allclose(result_dot, result_at):
  print("Results from both methods are identical.")
else:
    print("Results may differ due to rounding errors.")

Time taken for np.dot(): 2.276863300000059
Time taken for @: 2.0969662999999628
Results from both methods are identical.


# Q22

# Q23

In [9]:
# Generate a 2D array of random floats between 0 and 1
random_array = np.random.rand(4, 4)

# Create a Boolean mask for values less than 0.5
mask = random_array < 0.5

# Replace values less than 0.5 with their squares
random_array[mask] = random_array[mask]**2

print(random_array)

[[0.10446895 0.19813687 0.00667821 0.23299571]
 [0.70600179 0.04310791 0.11559863 0.73314431]
 [0.89907533 0.8374959  0.69199286 0.84861195]
 [0.71789846 0.87601508 0.01014837 0.18211911]]


# Q24

In [10]:
array = np.arange(25).reshape(5, 5)

# Extract the diagonal elements
diagonal = array.diagonal()

# Replace the elements of the middle row with zeros
array[2, :] = 0

# Flip the array vertically
array_flipped_vertically = np.flipud(array)

# Flip the array horizontally
array_flipped_horizontally = np.fliplr(array)

print("Original array:")
print(array)

print("\nDiagonal elements:")
print(diagonal)

print("\nArray with middle row replaced with zeros:")
print(array)

print("\nArray flipped vertically:")
print(array_flipped_vertically)

print("\nArray flipped horizontally:")
print(array_flipped_horizontally)

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Diagonal elements:
[ 0  6  0 18 24]

Array with middle row replaced with zeros:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Array flipped vertically:
[[20 21 22 23 24]
 [15 16 17 18 19]
 [ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]

Array flipped horizontally:
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [ 0  0  0  0  0]
 [19 18 17 16 15]
 [24 23 22 21 20]]


# Q25

# Q26

In [11]:
array = np.arange(200).reshape(10, 20)

# Reshape to (20, 10)
array_20x10 = array.reshape(20, 10)

# Reshape to (5, 40)
array_5x40 = array.reshape(5, 40)

print("Original shape:", array.shape)
print("Reshaped to (20, 10):", array_20x10.shape)
print("Reshaped to (5, 40):", array_5x40.shape)

Original shape: (10, 20)
Reshaped to (20, 10): (20, 10)
Reshaped to (5, 40): (5, 40)


the shape of the array changes while the size and dimensionality remain constant.

# Q27

In [12]:
large_array = np.random.randint(0, 1000, (1000, 1000))

# Print the original shape
print("Original shape:", large_array.shape)

# Reshape to (100, 10000)
reshaped_array = large_array.reshape(100, 10000)
print("Reshaped shape:", reshaped_array.shape)

# Flatten the array
flattened_array = large_array.ravel()
print("Flattened shape:", flattened_array.shape)

# Verify that the elements remain the same
if np.array_equal(large_array.flatten(), flattened_array):
    print("Elements remain the same after reshaping and flattening.")
else:
    print("Elements have changed.")

Original shape: (1000, 1000)
Reshaped shape: (100, 10000)
Flattened shape: (1000000,)
Elements remain the same after reshaping and flattening.


# Q28

In [15]:
matrix = np.random.randint(0, 10, (6, 6))

# Extract the upper triangular part
upper_triangular = np.triu(matrix)

# Set the lower triangular part to zero
matrix[np.tril_indices(6, k=-1)] = 0


print("Original matrix:")
print(matrix)

print("\nUpper triangular part:")
print(upper_triangular)

Original matrix:
[[8 6 6 4 3 8]
 [0 2 7 6 3 3]
 [0 0 6 9 4 7]
 [0 0 0 9 4 7]
 [0 0 0 0 7 9]
 [0 0 0 0 0 2]]

Upper triangular part:
[[8 6 6 4 3 8]
 [0 2 7 6 3 3]
 [0 0 6 9 4 7]
 [0 0 0 9 4 7]
 [0 0 0 0 7 9]
 [0 0 0 0 0 2]]
